### ISSUE TITLE
Max length question name stored incorrectly for drafts

### ISSUE THREAD

**Issue by chalo2000** [cuappdev/pollo-ios#390]
<details>
<summary>The original intended title</summary>

![still works!](https://user-images.githubusercontent.com/21962778/79698385-92ce1880-8256-11ea-830c-f8afb2e08fcd.gif)
</details>

<details>
<summary>How it displayed on drafts</summary>

![IMG_1508](https://user-images.githubusercontent.com/21962778/79698440-e93b5700-8256-11ea-8dfd-19e319d4481a.PNG)
</details>

**Comment by jackthmp** [comment]
wait it stored it as an empty string??? or it just doesn't display in the cell?

**Comment by chalo2000** [comment]
![acutally doesn't work](https://user-images.githubusercontent.com/21962778/79702092-1e07d800-8270-11ea-974d-9d104a0657c5.gif)

**Comment by chalo2000** [comment]
Unable to replicate with the same input text now..
